---
title: "Languages"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Languages}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

Scryfall archives Magic cards in 17 languages (including some unofficial
languages).

Each Card object indicates its language in the `lang` property using an ISO-like
code. When available, cards may also include their printed text in
`printed_name`, `printed_type_line`, and `printed_text` fields.

Please note that Oracle text is always English, per game rules. Cards printed in
non-English languages are a translation of the Oracle text at the time the card
was printed, but these texts do not receive errata.

Our support for multiple languages in older sets is limited. We are expanding
this data slowly over time.

The current languages are:

| Code  | Printed Code | Language            | Cards  | Examples                                                                               |
| ----- | ------------ | ------------------- | ------ | -------------------------------------------------------------------------------------- |
| `en`  | en           | English             | 63,650 | [Example Cards](https://scryfall.com/search?order=released&q=lang%3Aen&unique=prints)  |
| `es`  | sp           | Spanish             | 33,722 | [Example Cards](https://scryfall.com/search?order=released&q=lang%3Aes&unique=prints)  |
| `fr`  | fr           | French              | 34,481 | [Example Cards](https://scryfall.com/search?order=released&q=lang%3Afr&unique=prints)  |
| `de`  | de           | German              | 33,837 | [Example Cards](https://scryfall.com/search?order=released&q=lang%3Ade&unique=prints)  |
| `it`  | it           | Italian             | 34,135 | [Example Cards](https://scryfall.com/search?order=released&q=lang%3Ait&unique=prints)  |
| `pt`  | pt           | Portuguese          | 30,134 | [Example Cards](https://scryfall.com/search?order=released&q=lang%3Apt&unique=prints)  |
| `ja`  | jp           | Japanese            | 36,485 | [Example Cards](https://scryfall.com/search?order=released&q=lang%3Aja&unique=prints)  |
| `ko`  | kr           | Korean              | 14,076 | [Example Cards](https://scryfall.com/search?order=released&q=lang%3Ako&unique=prints)  |
| `ru`  | ru           | Russian             | 19,643 | [Example Cards](https://scryfall.com/search?order=released&q=lang%3Aru&unique=prints)  |
| `zhs` | cs           | Simplified Chinese  | 28,235 | [Example Cards](https://scryfall.com/search?order=released&q=lang%3Azhs&unique=prints) |
| `zht` | ct           | Traditional Chinese | 21,530 | [Example Cards](https://scryfall.com/search?order=released&q=lang%3Azht&unique=prints) |
| `he`  |              | Hebrew              | 1      | [Example Cards](https://scryfall.com/search?order=released&q=lang%3Ahe&unique=prints)  |
| `la`  |              | Latin               | 1      | [Example Cards](https://scryfall.com/search?order=released&q=lang%3Ala&unique=prints)  |
| `grc` |              | Ancient Greek       | 1      | [Example Cards](https://scryfall.com/search?order=released&q=lang%3Agrc&unique=prints) |
| `ar`  |              | Arabic              | 1      | [Example Cards](https://scryfall.com/search?order=released&q=lang%3Aar&unique=prints)  |
| `sa`  |              | Sanskrit            | 1      | [Example Cards](https://scryfall.com/search?order=released&q=lang%3Asa&unique=prints)  |
| `ph`  | ph           | Phyrexian           | 9      | [Example Cards](https://scryfall.com/search?order=released&q=lang%3Aph&unique=prints)  |
