structure(list(url = "https://api.scryfall.com/sets/zzz", status_code = 404L, 
    headers = structure(list(date = "Wed, 05 Jan 2022 05:19:09 GMT", 
        `content-type` = "application/json; charset=utf-8", `x-frame-options` = "DENY", 
        `x-xss-protection` = "1; mode=block", `x-content-type-options` = "nosniff", 
        `x-download-options` = "noopen", `x-permitted-cross-domain-policies` = "none", 
        `referrer-policy` = "strict-origin-when-cross-origin", 
        `access-control-allow-origin` = "*", `access-control-allow-methods` = "GET, POST, DELETE, OPTIONS", 
        `access-control-allow-headers` = "Accept, Accept-Charset, Accept-Language, Authorization, Cache-Control, Content-Language, Content-Type, DNT, Host, If-Modified-Since, Keep-Alive, Origin, Referer, User-Agent, X-Requested-With", 
        `access-control-max-age` = "300", `x-robots-tag` = "none", 
        `cache-control` = "public", `x-action-cache` = "HIT", 
        vary = "Accept-Encoding", `content-encoding` = "gzip", 
        `strict-transport-security` = "max-age=31536000; includeSubDomains; preload", 
        via = "1.1 vegur", `cf-cache-status` = "DYNAMIC", `expect-ct` = "max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\"", 
        `report-to` = "{\"endpoints\":[{\"url\":\"https:\\/\\/a.nel.cloudflare.com\\/report\\/v3?s=0q%2FJ0GDPHLki8fUIA%2FZmo8lMb4PBUsBwH0oF1M%2F5P%2FU2eR8Qm0FryAsFIt3rJQsnZ2OhdzzyXrWio%2B0PHTg5NZT9P1d6JDzen6fk2YWX%2BQW19VvMyU2s10cfXjm%2BbszX%2Fj7Wsh2b5G9SmwHBzAg%3D\"}],\"group\":\"cf-nel\",\"max_age\":604800}", 
        nel = "{\"success_fraction\":0,\"report_to\":\"cf-nel\",\"max_age\":604800}", 
        server = "cloudflare", `cf-ray` = "6c8a40021e074edd-GRU", 
        `alt-svc` = "h3=\":443\"; ma=86400, h3-29=\":443\"; ma=86400, h3-28=\":443\"; ma=86400, h3-27=\":443\"; ma=86400"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 404L, version = "HTTP/2", 
        headers = structure(list(date = "Wed, 05 Jan 2022 05:19:09 GMT", 
            `content-type` = "application/json; charset=utf-8", 
            `x-frame-options` = "DENY", `x-xss-protection` = "1; mode=block", 
            `x-content-type-options` = "nosniff", `x-download-options` = "noopen", 
            `x-permitted-cross-domain-policies` = "none", `referrer-policy` = "strict-origin-when-cross-origin", 
            `access-control-allow-origin` = "*", `access-control-allow-methods` = "GET, POST, DELETE, OPTIONS", 
            `access-control-allow-headers` = "Accept, Accept-Charset, Accept-Language, Authorization, Cache-Control, Content-Language, Content-Type, DNT, Host, If-Modified-Since, Keep-Alive, Origin, Referer, User-Agent, X-Requested-With", 
            `access-control-max-age` = "300", `x-robots-tag` = "none", 
            `cache-control` = "public", `x-action-cache` = "HIT", 
            vary = "Accept-Encoding", `content-encoding` = "gzip", 
            `strict-transport-security` = "max-age=31536000; includeSubDomains; preload", 
            via = "1.1 vegur", `cf-cache-status` = "DYNAMIC", 
            `expect-ct` = "max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\"", 
            `report-to` = "{\"endpoints\":[{\"url\":\"https:\\/\\/a.nel.cloudflare.com\\/report\\/v3?s=0q%2FJ0GDPHLki8fUIA%2FZmo8lMb4PBUsBwH0oF1M%2F5P%2FU2eR8Qm0FryAsFIt3rJQsnZ2OhdzzyXrWio%2B0PHTg5NZT9P1d6JDzen6fk2YWX%2BQW19VvMyU2s10cfXjm%2BbszX%2Fj7Wsh2b5G9SmwHBzAg%3D\"}],\"group\":\"cf-nel\",\"max_age\":604800}", 
            nel = "{\"success_fraction\":0,\"report_to\":\"cf-nel\",\"max_age\":604800}", 
            server = "cloudflare", `cf-ray` = "6c8a40021e074edd-GRU", 
            `alt-svc` = "h3=\":443\"; ma=86400, h3-29=\":443\"; ma=86400, h3-28=\":443\"; ma=86400, h3-27=\":443\"; ma=86400"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = ".api.scryfall.com", 
        flag = TRUE, path = "/", secure = FALSE, expiration = structure(1641440572, class = c("POSIXct", 
        "POSIXt")), name = "heroku-session-affinity", value = "REDACTED"), row.names = c(NA, 
    -1L), class = "data.frame"), content = charToRaw("{\n  \"object\": \"error\",\n  \"code\": \"not_found\",\n  \"status\": 404,\n  \"details\": \"No Magic set found for the given code or ID\"\n}"), 
    date = structure(1641359949, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 6.9e-05, 
    connect = 6.9e-05, pretransfer = 0.000196, starttransfer = 0.446967, 
    total = 0.447108)), class = "response")
